server:
  port: 9999
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
    session:
      timeout: 1800 # 60? * 30
  ssl:
    enabled: false
spring:
  config:
    activate:
      on-profile:
  thymeleaf:
    cache: false # false : html ??? ?? ??
    check-template-location: true
    prefix: classpath:/templates/ # ??
    suffix: .html
    enabled: true #????
  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #dev
    url: jdbc:mariadb://localhost:3306/sample-db
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

logging:
  level:
    root: info
    org.springframework.security: trace
    org.springframework.security.authentication: trace


ws:
  aes256key: sdk3FVk239fjkFeH34k6H39fjFvj323j